# Numpy / SciPy

In [17]:
import numpy

In [18]:
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.shape

(12,)

In [21]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a[2]

array([ 8,  9, 10, 11])

In [23]:
a[2][1]

9

In [24]:
a[:, 1]

array([1, 5, 9])

In [25]:
a[:, 2]

array([ 2,  6, 10])

In [27]:
a = a.transpose()
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])